# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instanc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.FileField(upload_to='uploads/')),
                ('name', models.TextField(max_length=100)),
                ('last_accessed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'files',
                'verbose_name': 'file',
            },
        ),
    ]
